apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn
  namespace: vpn
spec:
  ingressClassName: nginx
  rules:
    - host: http://192.168.31.13
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vpn
                port:
                  number: 80
                  targetPort: 8000
