apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-worker
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-worker
  template:
    metadata:
      labels:
        app: vpn-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: vpn-worker
          image: ghcr.io/itzmegoldi/vpn-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: vpn-config
            - secretRef:
                name: vpn-secret
