apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: vpn-secret

spec:

  refreshInterval: 1m

  secretStoreRef:
    name: vault-store
    kind: SecretStore

  target:
    name: vpn-secret

  data:
    - secretKey: APP_ENV
        remoteRef:
        key: vpn
        property: APP_ENV

    - secretKey: DATABASE_URL
        remoteRef:
        key: vpn
        property: DATABASE_URL

    - secretKey: DATABASE_PORT
        remoteRef:
        key: vpn
        property: DATABASE_PORT

    - secretKey: DATABASE_NAME
        remoteRef:
        key: vpn
        property: DATABASE_NAME

    - secretKey: DATABASE_USER
        remoteRef:
        key: vpn
        property: DATABASE_USER

    - secretKey: DATABASE_PASSWORD
        remoteRef:
        key: vpn
        property: DATABASE_PASSWORD

    - secretKey: REDIS_HOST
        remoteRef:
        key: vpn
        property: REDIS_HOST

    - secretKey: REDIS_PORT
        remoteRef:
        key: vpn
        property: REDIS_PORT

    - secretKey: REDIS_PASSWORD
        remoteRef:
        key: vpn
        property: REDIS_PASSWORD

    - secretKey: SERVER_CLIENT_NAME
        remoteRef:
        key: vpn
        property: SERVER_CLIENT_NAME

    - secretKey: SERVER_CLIENT_KEY
        remoteRef:
        key: vpn
        property: SERVER_CLIENT_KEY